/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAboutRouteImport } from './routes/_authenticated/app.about'
import { Route as AuthenticatedAppEntriesRouteImport } from './routes/_authenticated/app.entries'
import { Route as AuthenticatedAppMethodologyRouteImport } from './routes/_authenticated/app.methodology'
import { Route as AuthenticatedAppSharingRouteImport } from './routes/_authenticated/app.sharing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAboutRoute = AuthenticatedAppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEntriesRoute = AuthenticatedAppEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMethodologyRoute =
  AuthenticatedAppMethodologyRouteImport.update({
    id: '/methodology',
    path: '/methodology',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSharingRoute = AuthenticatedAppSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shared': typeof SharedRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/about': typeof AuthenticatedAppAboutRoute
  '/app/entries': typeof AuthenticatedAppEntriesRoute
  '/app/methodology': typeof AuthenticatedAppMethodologyRoute
  '/app/sharing': typeof AuthenticatedAppSharingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shared': typeof SharedRoute
  '/app/about': typeof AuthenticatedAppAboutRoute
  '/app/entries': typeof AuthenticatedAppEntriesRoute
  '/app/methodology': typeof AuthenticatedAppMethodologyRoute
  '/app/sharing': typeof AuthenticatedAppSharingRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/shared': typeof SharedRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/about': typeof AuthenticatedAppAboutRoute
  '/_authenticated/app/entries': typeof AuthenticatedAppEntriesRoute
  '/_authenticated/app/methodology': typeof AuthenticatedAppMethodologyRoute
  '/_authenticated/app/sharing': typeof AuthenticatedAppSharingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/shared'
    | '/app'
    | '/app/about'
    | '/app/entries'
    | '/app/methodology'
    | '/app/sharing'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/shared'
    | '/app/about'
    | '/app/entries'
    | '/app/methodology'
    | '/app/sharing'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/shared'
    | '/_authenticated/app'
    | '/_authenticated/app/about'
    | '/_authenticated/app/entries'
    | '/_authenticated/app/methodology'
    | '/_authenticated/app/sharing'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SharedRoute: typeof SharedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/about': {
      id: '/_authenticated/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AuthenticatedAppAboutRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/entries': {
      id: '/_authenticated/app/entries'
      path: '/entries'
      fullPath: '/app/entries'
      preLoaderRoute: typeof AuthenticatedAppEntriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/methodology': {
      id: '/_authenticated/app/methodology'
      path: '/methodology'
      fullPath: '/app/methodology'
      preLoaderRoute: typeof AuthenticatedAppMethodologyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sharing': {
      id: '/_authenticated/app/sharing'
      path: '/sharing'
      fullPath: '/app/sharing'
      preLoaderRoute: typeof AuthenticatedAppSharingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAboutRoute: typeof AuthenticatedAppAboutRoute
  AuthenticatedAppEntriesRoute: typeof AuthenticatedAppEntriesRoute
  AuthenticatedAppMethodologyRoute: typeof AuthenticatedAppMethodologyRoute
  AuthenticatedAppSharingRoute: typeof AuthenticatedAppSharingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAboutRoute: AuthenticatedAppAboutRoute,
  AuthenticatedAppEntriesRoute: AuthenticatedAppEntriesRoute,
  AuthenticatedAppMethodologyRoute: AuthenticatedAppMethodologyRoute,
  AuthenticatedAppSharingRoute: AuthenticatedAppSharingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SharedRoute: SharedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
